### ISSUE TITLE
Feature request: pad selections.

### ISSUE THREAD

**Issue by phyllisstein** [viablelab/bracket-padder#7]
Hey there! I hate to be a bother, but I wanted to run a little feature request by you after spending a few minutes getting nowhere on implementing it myself. I think it would be amazing if this package could inject padding after the built-in `bracket-matcher` package wrapped a selection in brackets---that is, if selecting `text` and hitting <kbd>{</kbd> yielded `{ text }`.

I tried to see if I could toss you a PR, but unfortunately didn't have much success: it looks like `bracket-matcher` already suppresses the editor's events on wrapping the selection. It feels like there _must_ be some way, but I'm afraid I'm out of my Atomic depth here.

Thanks in advance if you get a chance to look at it! And, of course, for all your work on this repo.

**Comment by mrwest808** [comment]
I can probably have a look at this some time during this week, I'll get back to you after investigating!

**Comment by mrwest808** [comment]
It seems like packages can [interact with each other](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/), but `bracket-matcher` doesn't expose any services. A couple of solutions comes to mind:

1. Pretty much replicate the behavior of wrapping selections from `bracket-matcher`, but with padding. Optimally paired with some options for more control of when this happens. This would require a note stating that [this option](https://github.com/atom/bracket-matcher/blob/275f373/package.json#L55-L59) in `bracket-matcher` would need to be disabled, and should perhaps be disabled by default in this package for that reason.
2. Create a user-level solution in Atom's [init file](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/), which would look something like:

```coffee
# From https://github.com/atom/underscore-plus
adviseBefore = (object, methodName, advice) ->
  original = object[methodName]
  object[methodName] = (args...) ->
    unless advice.apply(this, args) == false
      original.apply(this, args)

atom.workspace.observeTextEditors (editor) ->
  wrapSelectionWithPadding = (text, options) ->
    return unless ['(', '[', '{'].includes(text)

    editor.mutateSelectedText (selection) ->
      return if selection.isEmpty()

      # Proceed to wrap selection with padding, update selection etc.

  adviseBefore(editor, 'insertText', wrapSelectionWithPadding)
```

I rarely select anything since I use Vim mode, but I definitely see how this can be useful for others that don't. Hopefully I can take a stab at this soon, but feel free to look at the init file solution meanwhile!

**Comment by phyllisstein** [comment]
Thanks so much for the suggestion, and please forgive the delay in my response! Adding something to the init file worked beautifully. I realized about midway through that I actually didn't want what I'd originally asked for---padding _every_ selection on _every_ keystroke would have been a mistake for my workflow and probably others'---so I tweaked it such that selecting `{|foo|}` (where `|`s indicate the selection range) and hitting <kbd>Space</kbd> yielded `{ foo }`, which is more in keeping with the package's interface. Here's what I wound up with:

```js
'use babel';

import _ from 'underscore-plus'

const PAIR_REGEXP = /^([\{\[\(])(.*?)([\}\]\)])$/

atom.workspace.observeTextEditors(editor => {
  const wrapSelectionWithPadding = (text, options) => {
    if (text !== ' ') return true

    let didMutate = false

    editor.mutateSelectedText(selection => {
      if (selection.isEmpty() || !selection.isSingleScreenLine()) return

      let selectedRange = selection.getBufferRange()
      selectedRange.end.column += 1
      selectedRange.start.column -= 1

      let toPad = editor.getTextInBufferRange(selectedRange)

      if (toPad = PAIR_REGEXP.exec(toPad)) {
        const padded = ` ${ toPad[2] } `
        selection.insertText(padded, { select: true })
        didMutate = true
      }
    })

    return !didMutate
  }

  _.adviseBefore(editor, 'insertText', wrapSelectionWithPadding)
})
```

Thanks again for your guidance! I really appreciate it.

**Comment by mrwest808** [comment]
Awesome, I'm glad that you found a solution that works! I'm on vacation right now, but when I get back I'll link to your solution so that potential other users looking for the same functionality can implement the same solution.

**Comment by mrwest808** [comment]
Added a [Wiki page with recipes](https://github.com/viablelab/bracket-padder/wiki#recipes) and included your solution there.
